name: babylonia_terminal_launcher
description: "A launcher to play a certain anime game on linux"
publish_to: 'none'

version: 0.1.2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  yaru: ^4.1.0
  provider: ^6.1.2
  rinf: ^6.9.0
  protobuf: ^3.1.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  flutter_highlight: ^0.7.0
  fixnum: ^1.1.0
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  yaru_window: ^0.2.1
  package_info_plus: ^8.1.0
  flutter_markdown: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/Lee6.png
    - CHANGELOG.md
