[workspace]
resolver = "2"
members = [
  "babylonia-terminal",
  "babylonia-terminal-cli",
  "babylonia-terminal-gui",
  "babylonia-terminal-sdk",
]

[workspace.dependencies]
downloader = { git = "https://github.com/ALEZ-DEV/downloader" } # version = "0.2.7",
