name: Cli-release

on:
  push:
    tags:
      - 'cli-*'
env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: babylonia-terminal-cli
            asset_name: babylonia-terminal-cli
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create release
      run: |
        cd babylonia-terminal-cli
        cargo build --release --verbose
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: babylonia-terminal-cli/target/release/babylonia-terminal-cli
        asset_name: babylonia-terminal-cli
        tag: ${{ github.ref }}
